---
prairie_base_packages:
  RedHat:
    - curl
    - wget
    - kernel-modules-extra
    - tar
  Debian:
    - curl
    - wget
    - tar
  Suse:
    - python313-PyYAML


prairie_supported_families:
  - RedHat
  - Debian
  - Suse

prairie_manage_firewall: false

prairie_swap_size: "2G"
prairie_swappiness: "10"

prairie_kubernetes_distribution: ""
