rancher_ingress_tls_source: rancher   # rancher | secret | letsEncrypt (if you wire that up later)
rancher_chart_version: "2.13.0"
cert_manager_chart_version: "v1.19.2"
cert_manager_tag: "v1.19.2"
k3s_version: "v1.34.2+k3s1"
rke2_version: "v1.34.2+rke2r1"
helm_version: "v4.0.1"
longhorn_chart_version: "v1.10.1"

# prairie_kubernetes_distribution: "k3s" or "rke2"
prairie_kubernetes_distribution: "rke2"

prairie_tls_mode: "letsencrypt"

storage_engine: longhorn

