rancher_ingress_tls_source: rancher   # rancher | secret | letsEncrypt (if you wire that up later)
rancher_chart_version: "2.12.3"
cert_manager_chart_version: "v1.19.1"
k3s_version: "v1.31.14+k3s1"
rke2_version: "v1.31.14+rke2r1"
helm_version: "v3.18.2"
prairie_kubernetes_distribution: "rke2"

prairie_tls_mode: "letsencrypt"
vault_lets_encrypt_email: "you@example.com"   # use a real mailbox